---
kind: Pod
apiVersion: v1
metadata:
  name: minecraftserverpod
  labels:
    run: minecraftServer
spec:
  containers:
  - name: minecraftserver
    image: openhack/minecraft-server:2.0
    env:
      - name: "EULA"
        value: "TRUE"
    ports:
    - containerPort: 25565
      protocol: TCP
    - containerPort: 25575
      protocol: TCP
    resources: {}
    volumeMounts:
      - mountPath: "/data"
        name: volume
    imagePullPolicy: Always
    securityContext:
      capabilities: {}
      privileged: false
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: volume-minecraft
  restartPolicy: Always
  dnsPolicy: ClusterFirst
  serviceAccount: ''
status: {}