kind: Pod
apiVersion: v1
metadata:
  name: minecraftwebapp
  labels:
    run: minecraftwebapp
spec:
  containers:
  - name: minecraftwebapp
    image: jvaz/openhack_minecraftwebapp:latest
    ports:
    - containerPort: 80
      protocol: TCP
    - containerPort: 443
      protocol: TCP
    resources: {}
    imagePullPolicy: Always
    securityContext:
      capabilities: {}
      privileged: false
  restartPolicy: Always
  dnsPolicy: ClusterFirst
  serviceAccount: ''
status: {}