kind: Pod
apiVersion: v1
metadata:
  name: minecraftwebapi
  labels:
    run: minecraftwebapi
spec:
  containers:
  - name: minecraftwebapi
    image: felipecrestani/openhackapi:latest
    env:
    ports:
    - containerPort: 8888
      protocol: TCP
    resources: {}
    imagePullPolicy: Always
    securityContext:
      capabilities: {}
      privileged: false
  restartPolicy: Always
  dnsPolicy: ClusterFirst
  serviceAccount: ''
status: {}